.TH GSHUTDOWN 1 "2006-08-25"
.SH NAME
gshutdown \- An avanced shutdown utility
.SH SYNOPSIS
.B gshutdown
.br
.SH DESCRIPTION
.B GShutdown
is an advanced shutdown utility, which allows you to schedule the 
shutdown or the restart of your computer.

With it, you can simply and quickly choose the turn off time.

.SH AUTHOR
.B GShutdown
was written by GShutdown Team <https://github.com/Asher256/gshutdown/issues>
